version: '2'
   
services:
  posgresql:
    image: postgres:11.2
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "airmed"
      POSTGRES_USER: "airmed"
      POSTGRES_PASSWORD: "LYbAWCErGttRsP9y"
    volumes:
      - data_psql:/var/lib/postgresql/data
  redis:
    image: redis:4.0
    container_name: redis
    ports: 
      - "6379:6379"
    volumes:
      - data_redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    entrypoint: redis-server /usr/local/etc/redis/redis.conf

volumes:
  data_psql:
  data_redis:

# docker exec -t postgres pg_dumpall -c -U airmed > dump_`date +%d-%m-%Y"_"%H_%M_%S`.sql
