version: '2'
   
services:
  posgresql:
    image: postgres:9.4
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "airmed"
      POSTGRES_USER: "airmed"
      POSTGRES_PASSWORD: "LYbAWCErGttRsP9y"
    volumes:
      - data_psql:/var/lib/postgresql/data
volumes:
  data_psql:
