version: '2'
   
services:
  posgresql:
    image: postgres:11.2
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "airmed"
      POSTGRES_USER: "airmed"
      POSTGRES_PASSWORD: "To2Lf3eygAw8Amio8"
    volumes:
      - data_psql:/var/lib/postgresql/data
volumes:
  data_psql:

# docker exec -t postgres pg_dumpall -c -U airmed > dump_`date +%d-%m-%Y"_"%H_%M_%S`.sql
